/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDR					0x40023800UL
#define RCC_CFGR_OFFSET					0x08UL
#define RCC_CFGR_ADDR					(RCC_BASE_ADDR + RCC_CFGR_OFFSET)
#define RCC_CFGR_REG					*((volatile uint32_t *) RCC_CFGR_ADDR)

#define RCC_AHB1ENR_OFFSET				0x30UL
#define RCC_AHB1ENR_ADDR				(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)
#define RCC_AHB1ENR_REG					*((volatile uint32_t *) RCC_AHB1ENR_ADDR)

#define GPIOx_AFRH_OFFSET				0x24

#define GPIOA_BASE_ADDR					0x40020000
#define GPIOA_MODE_REG					*((volatile uint32_t *) GPIOA_BASE_ADDR)
#define GPIOA_AFRH_ADDR					(GPIOA_BASE_ADDR + GPIOx_AFRH_OFFSET)
#define GPIOA_AFRH_REG					*((volatile uint32_t *) GPIOA_AFRH_ADDR)

#define GPIOA_EN()						RCC_AHB1ENR_REG |= (1 << 0)
#define GPIOA_SET_MODE(pin, mode)		GPIOA_MODE_REG |= (mode << (pin*2)) // pin: 0 .. 15
#define GPIOA_SEL_AF0()					GPIOA_AFRH_REG |= (0 << 0)


int main(void)
{
	RCC_CFGR_REG &= ~(0x3 << 21); // clear bits 21 and 22.
    RCC_CFGR_REG |= (0x7 << 24);  // 110: division by 4

    // Configuration of GPIOA pin
    GPIOA_EN();
    GPIOA_SET_MODE(8, 0x2); // mode 0x10 Alternate function mode
    GPIOA_SEL_AF0();


	for(;;);
}
