/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int numbers[] = {456,345,678,567,890,456,3456,123,765,456,896,456,678,987,000,145,90};
int someData = 90;

void ArrayFillNumbers(int pNumbers[], unsigned int len){
	for(int i = 0; i < len; i++){
		pNumbers[i] = rand() % 1000;
	}
	someData = 5;
}

void DisplayNumbers(int *pNumbers, unsigned int len, char *pMessage){
	printf("%s",pMessage);

	for(int i = 0; i < len; i++){
		printf("%5d\t",pNumbers[i]);
	}

	printf("\n");
}

void SwapNumbers(int *x, int *y){
	int temp = *x;
	*x = *y;
	*y = temp;
#if 0
	void (*jumpAddr) (void);
	jumpAddr = (void*)0x20000009;
	jumpAddr();
#endif

	someData = 10;
}

void BubbleSort(int *pNumbers, unsigned int len){
	int i, j = 0, flag = 0;

	for(i = 0; i < len - 1; i++){
		flag = 0;

		for(j = 0; j < len - 1 - i; j++){
			if(pNumbers[j] > pNumbers[j+1]){
				SwapNumbers(&pNumbers[j], &pNumbers[j+1]);
				flag = 1;
			}
		}

		if(flag == 0) break;
	}
}

void InsertionSort(int *pNumbers, unsigned int len){
	int i, j, num;

	for(i = 1; i < len; i++){
		j = i-1;
		num = pNumbers[i];

		while((j > -1) && (pNumbers[j] > num)){
			pNumbers[j+1] = pNumbers[j];
			j--;
		}

		pNumbers[j+1] = num;
	}
}


int main(){
	unsigned int len = sizeof(numbers)/sizeof(int);

	ArrayFillNumbers(numbers, len);

	DisplayNumbers(numbers, len, "B-unsorted array: ");

	BubbleSort(numbers, len);

	DisplayNumbers(numbers, len, "B-sorted array: ");

	ArrayFillNumbers(numbers, len);

	DisplayNumbers(numbers, len, "I-unsorted array: ");

	InsertionSort(numbers, len);

	DisplayNumbers(numbers, len, "I-sorted array: ");

	return 0;
}
















