/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f42xxx.h>
#include <stm32f42xxx_gpio.h>
#include "main.h"

#define LED_RED			pin14
#define LED_GREEN		pin13
#define BUTTON			pin0

void GPIO_Config(GPIO_Config_t *gpio_config);
void RCC_Config(void);
void delay(void);

int main(void)
{
	GPIO_Config_t gpio_config;

	bool_t flag = false;

	RCC_Config();
	GPIO_Config(&gpio_config);

	//GPIO_WritePin(GPIO_PORTG, LED_RED, reset);
	//GPIO_WritePin(GPIO_PORTG, LED_GREEN, set);

	/* Loop forever */
	while(true) {
		delay();
		GPIO_TogglePin(GPIO_PORTG, LED_RED);
		GPIO_TogglePin(GPIO_PORTG, LED_GREEN);
		delay();
		if (GPIO_ReadPin(GPIO_PORTA, BUTTON))
			flag = true;
		if (GPIO_ReadPin(GPIO_PORTA, BUTTON) != flag) {
			flag = false;
			GPIO_WritePin(GPIO_PORTG, LED_GREEN, set);
			GPIO_TogglePin(GPIO_PORTG, LED_RED);
		}
	}
}

void RCC_Config(void) {
	/* RCC CR modify */
	RCC_CR_Bits->hse_on = set;

	while(!(RCC_CR_Bits->hse_rdy)); /* wait for HSE ready */

	RCC_CFGR_Bits->sw = HSE_osc;
}

void GPIO_Config(GPIO_Config_t *gpio_config) {
	gpio_config->port = gpiog;
	gpio_config->pin = LED_RED|LED_GREEN;
	gpio_config->mode = output;
	gpio_config->type = push_pull;
	gpio_config->pupd = no_pull;
	gpio_config->speed = medium;

	GPIO_Init(GPIO_PORTG, gpio_config);

	gpio_config->port = gpioa;
	gpio_config->pin = BUTTON;
	gpio_config->mode = input;
	gpio_config->type = push_pull;
	gpio_config->pupd = no_pull;
	gpio_config->speed = medium;

	GPIO_Init(GPIO_PORTA, gpio_config);
}

void delay(void) {
	for(int i = 0; i < 250; i++)
		for(int j = 0; j < 500; j++);
}
