/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f42xxx.h>
#include <stm32f42xxx_gpio.h>
#include "main.h"

#define LED_RED			pin13
#define LED_GREEN		pin14

void GPIO_Config(GPIO_Config_t *gpio_config);
void RCC_Config(void);
void delay(void);

int main(void)
{
	GPIO_Config_t gpiog_config;

	RCC_Config();
	GPIO_Config(&gpiog_config);
    /* Loop forever */
	GPIO_WritePin(GPIO_PORTG, LED_RED, reset);
	GPIO_WritePin(GPIO_PORTG, LED_GREEN, set);

	while(true) {
		for(int k = 0; k < 10; k++){
			delay();
			GPIO_TogglePin(GPIO_PORTG, LED_RED);
			GPIO_TogglePin(GPIO_PORTG, LED_GREEN);
		}
		GPIO_DeInit(&gpiog_config);
		delay();
		delay();
		delay();
		GPIO_Config(&gpiog_config);
	}
}

void RCC_Config(void) {
	RCC_CR_Bits *cr_bits;
	RCC_CFGR_Bits *cfgr_bits;

	cr_bits = (RCC_CR_Bits*) &RCC->CR;
	cfgr_bits = (RCC_CFGR_Bits *) &RCC->CFGR;

	/* RCC CR modify */
	cr_bits->hse_on = set;

	while(!(cr_bits->hse_rdy)); /* wait for HSE ready */

	cfgr_bits->sw = set;
}

void GPIO_Config(GPIO_Config_t *gpio_config) {
	gpio_config->port = gpiog;
	gpio_config->pin = pin13|pin14;
	gpio_config->mode = output;
	gpio_config->type = push_pull;

	GPIO_Init(GPIO_PORTG, gpio_config);
}

void delay(void) {
	for(int i = 0; i < 500; i++)
		for(int j = 0; j < 500; j++);
}
